name: london-rentals
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.12
  - jupyterlab
  - matplotlib
  - pandas
  - scikit-learn
  - xgboost
  - statsmodels
  - folium
  - geopandas
  - contextily
prefix: /opt/miniconda3/envs/london-rentals
